// <auto-generated />
namespace OnlineShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class reportOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reportOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "202109151343263_reportOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
